### ISSUE TITLE
purple color dont work

### ISSUE THREAD

**Issue by gost442** [KeithGDR/chat-processor#1]
purple color dont work

**Comment by crashzk** [comment]
If it's for the CSGO game it doesn't work because the color purple SPEC uses, something like that I believe.

**Comment by NaathySz** [comment]
try use _{teamcolor}_ or _\x03_ instead. _{teamcolor}_ and _\x03_ is always purple if message is from server.
Also, we dont know where you are trying to use the color, but it can help you or someone.

**Comment by KeithGDR** [comment]
This is hyper game specific, be sure you're using the appropriate colors available for your specific game.
