### ISSUE TITLE
Color support for SDK 2013 mods is limited

### ISSUE THREAD

**Issue by dysphie** [KeithGDR/chat-processor#3]
`AddColors` in `colorvariables.inc` wrongly assumes that non-SDK2009 games can't support custom colors.
While this might be true for CSGO, SDK2013 mods like No More Room in Hell support the `\x07XXXXXX` format just fine.

Not sure what the best approach is here tbh, simply replacing the `IsSource2009()` check could break other stuff. `multicolors.inc` might handle this better?

**Comment by KeithGDR** [comment]
I'm down to change the colors include Multicolors still feels to me like the Frankenstein of color includes.

**Comment by KeithGDR** [comment]
Added the SDK2013 engine to the list of available engine which supports custom colors.
