### ISSUE TITLE
Feature to block chat from spectator players

### ISSUE THREAD

**Issue by crashzk** [KeithGDR/chat-processor#6]
Currently, running the plugin on competitive servers, when a player that is spec sends a message on say(y) all players that are on the teams, whether TR or CT can see the message, even if the team players are alive they can see it the message still from the spec player.

Feature that I would like to be added would be to create a cvar so I can block it, team player will only be able to view the spec message when they are dead.

**Comment by KeithGDR** [comment]
Added a new ConVar specifically for spectators in the newest update.

**Comment by crashzk** [comment]
@drixevel-dev ConVar theoretically worked. https://github.com/drixevel-dev/chat-processor/commit/abfbeb4c45011980229ce7c5183149dca3c63d5f

However, what I would like is that, after the players of the CT and TR teams are dead, they can still see the say of the spec, not alive.

Activating the cvar that he added completely blocks the say of the SPEC, even if the players on the team are alive or dead, the say does not show them, only the spec can see it apparently.

I tried to help with some devs and they told me that apparently they need to make some changes here: https://github.com/drixevel-dev/chat-processor/blob/main/scripting/chat-processor.sp#L272-L296

Quoting a message from one of the devs I sought help with:
```
Hi, probably you need to tweak something in here

https://github.com/drixevel-dev/chat-processor/blob/main/scripting/chat-processor.sp#L272-L296

recipient contains the user ids of the player that will receive the message send by the player
```
I'm waiting for a return, thanks for the hour.

**Comment by crashzk** [comment]
@drixevel-dev ConVar theoretically worked. https://github.com/drixevel-dev/chat-processor/commit/abfbeb4c45011980229ce7c5183149dca3c63d5f

However, what I would like is that, after the players of the CT and TR teams are dead, they can still see the say of the spec, not alive.

Activating the cvar that he added completely blocks the say of the SPEC, even if the players on the team are alive or dead, the say does not show them, only the spec can see it apparently.

I tried to help with some devs and they told me that apparently they need to make some changes here: https://github.com/drixevel-dev/chat-processor/blob/main/scripting/chat-processor.sp#L272-L296

Quoting a message from one of the devs I sought help with:
```
Hi, probably you need to tweak something in here

https://github.com/drixevel-dev/chat-processor/blob/main/scripting/chat-processor.sp#L272-L296

recipient contains the user ids of the player that will receive the message send by the player
```
I'm waiting for a return, thanks for the hour.
