### ISSUE TITLE
Question. What are the disadvantages of using `CPrintToChat()` instead of `SayText2`?

### ISSUE THREAD

**Issue by IL0co** [KeithGDR/chat-processor#7]
In the source code, I saw that after all the manipulations you return a message to the chat using the usual `PrintToChat()`, and not like in other similar plugins via `SayText2`. What are the downsides of doing so?

**Comment by KeithGDR** [comment]
Chat-Processor uses the colors include 'colorvariables.inc' which helps with color tagging and makes it a lot simpler for people to color code their text. It uses a function inside of that include called 'CPrintToChat()' instead which is just a huge wrapper to do the string manipulation.

'PrintToChat()' by itself is essentially just a wrapper for 'SayText2' but we add a few extra steps for the reasons above, it just replaces those tags with whatever the engine equivalent of the color codes built into the engine are. The reason we call `CSayText2()` in the `colorvariables.inc` include sometimes is just to set the author.
