### ISSUE TITLE
[CS:GO] "/configs/chat_processor.cfg" colors

### ISSUE THREAD

**Issue by Ketz1337** [KeithGDR/chat-processor#8]
Sorry, I may have made a mistake, but I thought I'd report it. When I compile the latest plugin with the latest "colorvariables.inc" file, the coloring in the "/configs/chat_processor.cfg" file doesn't work. However, the latest plugin with the older "colorvariables.inc" file works.

And the last three lines of the "/configs/colovariables/global.cfg" file are different from the old file.

**"/configs/chat_processor.cfg" file:**
![chat_processor_configs](https://user-images.githubusercontent.com/23225942/216365923-08023f9c-2e22-48a0-8538-6e7a0e62f6bc.png)

**Old "colorvariables.inc":**
![chat_processor_colorcariables_old](https://user-images.githubusercontent.com/23225942/216365914-daba3ae7-8a34-4011-930d-c87de45111a7.png)

**New "colorvariables.inc":**
![chat_processor_colorvariables_new](https://user-images.githubusercontent.com/23225942/216365918-55575d6d-9d47-4d6f-a8d1-9fa45393f89c.png)

**Old "/configs/colorvariables/global.cfg":**
![colorvariables_global_old](https://user-images.githubusercontent.com/23225942/216365928-ea677689-66a5-465d-a126-ac12cd5fa1be.png)

**New "/configs/colorvariables/global.cfg":**
![colorvariables_global_new](https://user-images.githubusercontent.com/23225942/216365925-539b6ae1-4d77-4a59-865f-ffc63f7c8bd4.png)

**Comment by KondiU** [comment]
same problem here

**Comment by crashzk** [comment]
I believe it has to do with my problem also using HexTag, as I mentioned in the hextags issues.

https://github.com/Hexer10/HexTags/issues/95

**_Note: At least in CSGO the bug exists, other games just testing._**

**Comment by crashzk** [comment]
@VaaLaaKi @KondiU test this fix: https://github.com/crashzk/chat-processor/tree/fix-ColorsChat-ChatGOTV

**Comment by crashzk** [comment]
Fix on latest commit 5c855a0632cc795a6d3e377e03138e6eecc18bb4
